version: "3"
services:
    chef-server:
        build:
            context: .
            args:
                WITH_MANAGE: 1
        image: trueability/chef-server:dev
        environment:
            EXTERNAL_URL: "https://localhost"
        volumes:
            - "./tmp/data:/var/opt"
        privileged: true
    nginx:
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./tmp/data/opscode/nginx/ca/:/etc/nginx/ssl"
